name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - feature/add-aca-deployment-tf


jobs:
  deploy:
    runs-on: ubuntu-latest

   # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_VAR_ghcr_username: ${{ github.actor }}
          TF_VAR_ghcr_token: ${{ secrets.GITHUB_TOKEN }}