name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - feature/add-aca-deployment


jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}


      - name: Deploy to ACA
        run: |
          az containerapp create \
            --name schoolaccount-alpha-app \
            --resource-group contapps \
            --environment contappmra \
            --image ghcr.io/dfe-digital/schoolaccount-alpha-app:${{ github.event.workflow_run.head_branch }} \
            --target-port 8080 \
            --ingress external \
            --registry-server ghcr.io \
            --registry-username ${{ github.actor }} \
            --registry-password ${{ secrets.GITHUB_TOKEN }}