name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - feature/add-aca-deployment


jobs:
  deploy:
    runs-on: ubuntu-latest

   # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to Container Apps Environment
        run: |
          az containerapp create \
            --name schoolaccount-alpha-app \
            --resource-group s268d01rg-uks-sa-poc \
            --environment s268d01ace-sa-poc \
            --image ghcr.io/dfe-digital/schoolaccount-alpha-app:latest \
            --target-port 8080 \
            --ingress external \
            --registry-server ghcr.io \
            --registry-username ${{ github.actor }} \
            --registry-password ${{ secrets.GITHUB_TOKEN }}